### ISSUE TITLE
采集时遇到问题，输入的密文不会影响输出的密钥

### ISSUE THREAD

**Issue by SDust66** [lkcp/cw305-kyber#1]
我在Chipwhisperer-Lite+CW305上运行代码时遇到问题，问题描述如下
bitstream文件使用了仓库里提供的`[cw305_ecc_p256_pmul_top.bit](https://github.com/lkcp/cw305-kyber/blob/master/cw305_kyber/cw305_kyber.runs/impl_1/cw305_ecc_p256_pmul_top.bit)`，软件端进行了如下修改
1. 参考README文件，在`def __init__(self)`中修改了`self.bytecount_size = 10`
2. 在`def run_pmult`中修改了`self.fpga_write(self.REG_CRYPT_K, list(int.to_bytes(k, length=768, byteorder='little')))`，将`length`由32调整为768，使其可以接收长度为6144的密文输入

在运行时，我尝试了`k = 0x452669cf1da9d68725722702da5c3c5a74ba4acb9761387de5974b2bded04a8f9f9d6e4dba8bf06238b42177233602aa9d985dd8e05893efa1ab47b28356ea2278460fecfb46cb88f492ecec608501fe17526ccdd071c8a1f62e92d63106acd20ca13c6f182508a76a9fe9ffa3beae87856738c540295120b3911cbcccde0fbe5455b61bea0b267deef3e9c2508ce50606d840cddbbfd960d06e427a9e86cc951dac860cdf5dccc3470ad706302eeb8d7cd787554e6ca0e7740c464113d1344392ba2a26d3f5d54716f3d5b01d2dbfd73e0eb1c7ee5c3089f509a4e6dbdcbf2e7b809ca133f1b073a86522b4a53226bb90fa8c68fbf5b4e17d170fbc4704fcdfbbbc0b22449dab21a2c6bf4f5f471f4a3ded31665e1647a484a9e4586d76a164b7df6da32fe98a50deae3e7732ad1cdbc2bdc14f5260ec3ac62c682851522b664fa3b75bcc9defc51e529e380ca0c30c01d1ab2ecac74c7da08ea05cde203a3de9ab69dd4381861a2217353a5d05c0ff821dd3e79ef5dff4028e88c026b1feefb6bfe9363efb8d83f276f92324d76481c21409e766dc46e1de234c06ee2dd28ea170c9b180035cae62b2532bbbadba41c475cc4698aa635d449cffe9bca633ad10e210e2901dab4899d2c3ac75aa17606fbb7175a4c387b01e4e2148669f6d2618b25b837e6deb4c9817644125af75bd40af90ec0204bd8b0911fb28224eb66173aa37cafca84f23ff2c710548679e5a066c6b07d2a82bcfc2492f04ba8c6be9262198eaa1ce7010c5be6d50069332915e776ca3c00022c1367501633e5613d05bbd24c7b10702551d4267c0b4f6659a998639613188c863402b034d1f12539c8f8f57fa13f586a08bf6fb271d0866ea0a97a29a253f29ae5ebff61fcbaea8c5804ede8cbe2c30d96d4954885457be27b209851b2d405b4deaeeeda1365dbd0d5bb72ba42c69517fa0f21f671c51bb06cec632e4f8732f583cc79b5a19234a8c03b54c48a5f33ea5ce139c80df6506f812052d55ce939847e5eb63bec2cac5550039a9dea3273a063dd1ffb8d639bf9144a044cb9fa4234e4b0cd6fe4cc1875e`(来自tb.v文件)
和`k = 0xEDF24145E43B4F6DC6BF8332F54E02CAB02DBF3B5605DDC90A15C886AD3ED489462699E4ABED44350BC3757E2696FBFB2534412E8DD201F1E4540A3970B055FE3B0BEC3A71F9E115B3F9F39102065B1CCA8314DCC795E3C0E8FA98EE83CA6628457028A4D09E839E554862CF0B7BF56C5C0A829E8657947945FE9C22564FBAEBC1B3AF350D7955508A26D8A8EB547B8B1A2CF03CCA1AABCE6C3497783B6465BA0B6E7ACBA821195124AEF09E628382A1F914043BE7096E952CBC4FB4AFED13609046117C011FD741EE286C83771690F0AEB50DA0D71285A179B215C6036DEB780F4D16769F72DE16FDADAC73BEFA5BEF8943197F44C59589DC9F4973DE1450BA1D0C3290D6B1D683F294E759C954ABE8A7DA5B1054FD6D21329B8E73D3756AFDA0DCB1FC8B1582D1F90CF275A102ABC6AC699DF0C5870E50A1F989E4E6241B60AAA2ECF9E8E33E0FFCF40FE831E8FDC2E83B52CA7AB6D93F146D29DCA53C7DA1DB4AC4F2DB39EA120D90FA60F4D437C6D00EF483BC94A3175CDA163FC1C2828BE4DBD6430507B584BB5177E171B8DDA9A4293C3200295C803A865D6D2166F66BA5401FB7A0E853168600A2948437E036E3BF19E12FD3F2A2B8B343F784248E8D685EB0AFDE6315338730E7A1001C27D8D2A76FA69D157BA1AC7AD56DA5A8C70FE4B5B8D786DC6FC0566BA8E1B8816334D32A3FB1CE7D4D5E4C332AF7B003D091741A3D5C965292255DFF8ED2BBF1F9116BE50C17B8E548748AD4B2E957BBD1953482A2E1718CEC66CD2C81F572D552B7187885E6B8943D6431413C59EBB7E036048490BE5289E95B20A89E8B159F61A9A9886E147568F4C9021F362F02688A1C8C3BB0D24086880E55B6EDB43F3745D2C166DC1CB743C76FE6BE523A893CC764D16435C37851252A81E2FFBA0F18971A3DEE37D4877CB928E36E5235037A6B2057897D518A5F0E348E3AB6D5B52DFC60757F3B41A4FEC7828F1DEEAF4587CCC8EADF647F4D203B2FAA05A649B582340CB4CACE57A30711BE752FACF0227D0A80C4128442DDC544BE805B9CFE8FE9B1237C80F96787CD9281CCF270C1AFC0670D`(来自Kyber在NIST官网公布的KAT文件)
使用不同的k在运行`get_traces`采集能量迹返回后，返回值`textout`中的`Rx`都是`24265196513877281568320946292574093346582640214847958356118662587992824783308`，对应十六进制`0x35a59d5191b23bd865d4d822e52bf09c73e246a3a84386a00b3a9b332d5aa1cc`。
我不清楚哪里遇到了问题，期待得到您的帮助

**Comment by lkcp** [comment]
你好，
1. 你有试过 KAT 中的测试向量在 testbench 中的结果吗？
2. 能否提供一下你上位机的通信部分，如何将数据发送给开发板以及如何读取的？
谢谢。

**Comment by SDust66** [comment]
我在cw官方的issue中发现了类似的问题，里面提到是固件版本太老导致输入超过64字节时会出现问题。我印象中我在今年收到开发板后更新过固件，不知道为什么没有生效。刚刚我使用cw5.7.0重新更新了固件，现在可以正常计算并输出结果了。
由于问题解决了，我认为可以关闭这个问题了。感谢您的回复，祝您2025年一切顺利！
